### ISSUE TITLE
Clicking on the marker field floods the console with errors

### ISSUE THREAD

**Issue by inhalt120g** [KoBeWi/Godot-Simple-TODO#5] opened 2024-03-03 06:55 UTC
Clicking on any "marker" field (the leftmost "check" field in each row) floods the console with errors and keeps printing the errors as long as the LMB is pressed, which is very impractical when attempting to drag a note from one column to another (the whole row / entry just disappears and then appears in a new spot, even in a collapsed column).
res://addons/SimpleTODO/TODOItem.gd:58 - Cannot call method 'get_parent' on a null value.

![image](https://github.com/KoBeWi/Godot-Simple-TODO/assets/106015575/d856a649-cedf-4ccd-8647-efd3b799a926)

**Comment by KoBeWi** [comment] 2024-03-03 12:15
Can't reproduce it. What Godot and addon versions are you using?

**Comment by kshitijaucharmal** [comment] 2024-05-09 13:53
Same error here
Godot version: v4.2.2.stable.arch_linux

Tried the assetlib version as well, drag and drop doesn't work at all in that one.

**Comment by KoBeWi** [comment] 2024-05-10 10:35
Fixed by 6ea629c3081fbfd28ce59a47e88a5ab5f04fcbe6

**Closed as completed by KoBeWi** 2024-05-10 10:35 UTC

**Comment by kshitijaucharmal** [comment] 2024-05-10 11:54
Thanks!
